import React from 'react'
import './StageDirections.css';
import FadeIn from '../CourseGoalItem/FadeIn';
import Image1 from '../Images/beyond.webp'
import Image2 from '../Images/drinkingGuzzle.png'
import Image3 from '../Images/onPhone.png'
import Image4 from '../Images/tinyMan.png'
import Image5 from '../Images/cityOnFire.png'


const StageDirections = (props) => {

  let action;
  if(props.courseGoals.length === 0){
    action = (
        <FadeIn><div className='directions'><h3>Panlaughlin and Vrocum settle down in their sparsely-furnished living room to watch a banned telenovela. Those caught watching it face up to 50 years in prison.</h3><h3>To keep the electricity running, they must talk incessantly.</h3><h3>Our collective dreams are of great worth to the corporations.</h3></div></FadeIn>
    );} else if (props.courseGoals.length === 1) {
      action = (
        <FadeIn><h1 className='titleName'>FIRESALE: A Telenovela</h1><img src={Image1} alt='adam touching the void'/><h2>by David Valdez Taylor</h2></FadeIn>
      )
    } else if (props.courseGoals.length === 2) {
      action = (
        <FadeIn><h3>The story begins...</h3><br></br><p> “Well, sir. Since we installed our more accurate meter reader, we have discovered that you use far more electricity than assumed under the previous tariff. We would be willing to discuss a different payment plan that will save you money in the long run. Is this something you would be interested in?”</p><p>Black rubber around Henry&#39;s throat palpates his vocal cords while electric needles jounce his tongue. He tries to avoid his reflected gaze in the office window&#39;s mirrored surface. Cold water runs down his wrist to the elbow as he sponges more soapy water onto its surface. His reflection momentarily wavers.</p><p>Mrs Stephens appears below and waves frantically for him to come down. He presses a button that lowers the cradle to the ground.</p><p>“The rates we have quoted will remain in place until April 2078, then will review the situation so there is nothing for you to worry about. You should receive an e-mail within the next week with your revised plan. Thank you and enjoy the rest of your day.”</p><p>Henry pulls the tubing out of his mouth and spits the taste of rubber into the rhododendrons.</p><p>“There&#39;s somebody waiting to speak to you in reception. It looks official.”</p><p>She is displeased, her hair a nest of white curls that shuffles in the wind like a restless mammal.</p><p>This interruption, she states, will come out of your wage.</p><p>A middle-aged broad-shouldered man in a black suit and tie waits by the desk. His neck is stretched to its utmost atop which sits a small bald head furiously chewing gum.</p><p>“Mr Kikker, I presume?” He says. His hands remained firmly clasped behind his back as Henry reaches for a handshake. “I am Detective Jansen,” he draws out a tattered blue lanyard. Details on the card have faded to a meaningless grey smudge. “I work for the Library Investigations department. You better take a seat!”</p></FadeIn>
      )
    } else if (props.courseGoals.length === 3) {
      action = (
        <FadeIn><p>He declares the last loudly to Henry and, by an inclination of his head, to the rest of the room. Toby on the reception desk films them with his smartphone.</p><p>“Oh, dear, Henry!” Mrs Stephens stands by the door, hands on her hips. “What has he done?”</p><p>“This young man borrowed a copy of Wide Sargasso Sea by Jean Rhys fifteen years ago and never returned it,” Jansen thrusts his hands into his pockets and shrugs as if all the evils he had seen has made him lose faith in humanity. “People think that we will never catch up with them and they can change their address or move away. Our arm is long, however. Long and unrelenting.”</p><p>To illustrate this point, he rolls up one shirtsleeve and thrusts out a long pale arm at Mrs Stephens upon which is tattooed a large watchful eye. She and Toby nod appreciatively.</p><p>Henry dimly recalls having used the library several times in his youth.</p><p>His colleagues emerge from the entrance to the office drawn by the activity in reception, the headsets that make them look like anthropomorphic crocodiles are on pause as they nod and point at the intricate tattoo.</p><p>“What can he do?” Mrs Stephens says, now laying her hand on Henry&#39;s shoulder. He flinches. She was keen to take on the appearance of a good boss, always on the workers side, but only when she had an audience. “You see, Mr Kikker here only came out of a stasis pod two months ago. He was in there for four years unemployed, only taking one meal a day to conserve energy and sleeping the rest of the time. He must have borrowed the book before the library was sold off?”</p><p>“We inherited all the library debts,” says Jansen, his shoulders drop. “We had to sell off most of the stock. We only have four books left in the city&#39;s whole library system.”</p><p>Jansen sits down on the bench.</p><p>“My sister was in a stasis pod for a few months. It&#39;s no way to live.” He sighs exaggeratedly. “I shouldn&#39;t do this, but I&#39;m going to delay your arrest. Normally I would simply process you here and now. Instant conviction and sentencing. Off to our gulag! I have that authority!” He boasts.</p><p>Jansen declares to the small crowd standing behind the reception desk that he will give Henry two weeks to find the book or a replacement and bring it to the library in lendable condition. Failure will see him carted off to the book mines for five years and a day, such was the mandated punishment.</p><p>He points at Henry for an uncomfortable length of time, his thick eyebrows downturned in warning, before he hands over a citation and marches off through the glass doors.</p><p>Mrs Stephens shoos the gawkers back to work.</p><p>Henry, hands outstretched, looks to say something to her.</p><p>“Don&#39;t say sorry! Get back outside and wash those windows, Henry,” she says. “Those calls won&#39;t answer themselves.”</p><p>* * *</p></FadeIn>
      )
    } else if (props.courseGoals.length === 4) {
      action = (
        <FadeIn><h1>*Speak more*</h1><h1>*Enunciate your words*</h1><h1>*Be productive*</h1><h1>*Dream big!*</h1></FadeIn>
      )
    } else if (props.courseGoals.length === 5) {
      action = (
        <FadeIn><div className='video'><iframe src="https://www.youtube.com/embed/k5Kd1jn84V0?controls=0" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" ></iframe></div><div className='videoDialogue'><h3>Panlaughlin is disheartened by the voice broadcasting from the wall speaker and turns his attention away from the telenovela to watch a video on his phone, of himself as a young man.</h3></div></FadeIn>
      )
    } else if (props.courseGoals.length === 6) {
      action = (
        <FadeIn><h3>Vrocum snatches at the phone and directs Panlaughlin's attention back to the big screen.</h3><h3>Such sentimentalism is everything they are trying to escape from.</h3></FadeIn>
      )
    } else if (props.courseGoals.length === 7) {
      action = (
        <FadeIn><p>Henry barrels into the kitchen to get his bottle of Guzzle Guzzle from the fridge. Hives have broken out in itchy and unsightly blotches down his nose and cheeks. His flatmate, Simon, sits on the couch and stares blankly forward, his gaze lost to his MMORPG where he is an elf or some such creature. The VR lenses stain his eyes creamy white.</p><p>The Guzzle Guzzle saturates Henry&#39;s mouth in its bittersweet wash and he momentarily forgets about his anxiety.</p><p>He can&#39;t remember anything about Wide Sargasso Sea. He remembers next to nothing about any book he has read.</p><p>A feeling of expansiveness rises in his chest as the chemical flow makes him feel heroic, like a giant clambering effortlessly over rocks and shoals through a drunken sea.</p><p>“Guzzle Guzzle is not supposed to be drunk every day, Henry.” Simon rubs at his red streaming eyes, lenses now extracted. “It&#39;ll give you early Alzheimer&#39;s.”</p><p>Henry tries to respond but can only drool at this moment.</p><p>Simon picks up Henry&#39;s citation and reads it quickly, his eyes widening as he reaches the end.</p><p>“Well, then,” Simon mutters, “it looks like I&#39;m going to have to find a new flatmate.” He brings the letter closer to his face as if trying to find some watermark that will guarantee its authenticity. “I&#39;m guessing that the book is irretrievably lost. Those library people don&#39;t fuck around, Henry. You&#39;re going to have to steal a replacement. There&#39;s no way you can afford to buy one.</p><p>“I think you&#39;ve gone about living your life all wrong and this is just another result of the terrible decision you made in studying Drama at university,” he leans back as he prepares to digress on this most delectable topic. He had brought it up several times in the past month after he had found Henry&#39;s degree under the utensils in the kitchen drawer.</p><p>“Practical systems of thought are what is in demand. You should&#39;ve done computer programming or economics or business studies, not wishy-washy arts. You must be utterly exceptional to succeed in that field. I&#39;ve known you for a long time and you are not exceptional.</p></FadeIn>
      )
    } else if (props.courseGoals.length === 8) {
      action = (
        <FadeIn><p>“Even fifteen years ago, books were passé. What were you thinking?! Neuroblasting direct entertainments is all that there is or should be.</p><p>“My brother is a lawyer, you know, but I don&#39;t think even he can help you appeal. It&#39;s an open and shut case. I can&#39;t help that your memory is also screwed by the Guzzle Guzzle and all that time in a stasis pod. You should try and get your social media license reactivated so you can find out what you were doing at the time.”</p><p>Henry sits down heavily on the couch. The combination of having his mouth talked all day and the Guzzle Guzzle makes his tongue feel like a large cold slug. He clasps it between thumb and forefinger.</p><p>“Fifteen years ago!” Simon raises his eyebrows in astonishment. “You may as well try to remember the Stone Age. Getting a social media license going back that far will cost a bomb. Even mine only goes back two years and I can&#39;t remember anything past maybe seven years. You&#39;re going to have to get another job or something. Maybe use that to leverage a loan. And before you ask, I can&#39;t lend you any money,” he frowns. “I&#39;d never get it back.” </p><div className='images'><img src={Image2} alt='at the fridge'/></div>
        </FadeIn>
      )
    } else if (props.courseGoals.length === 9) {
      action = (
        <FadeIn><p>* * *</p><p>Henry activates the bathroom break protocol and takes off the prosthetic. The computer screen in front of him displays a countdown from five minutes. He tries not to look around, seeing a depressing reflection of his own bleak situation in the dark-ringed lifeless eyes of his colleagues, even though the room echoed with their bright cheery voices.</p><p>Inside the staff toilets a bald man in a baby blue tracksuit is hunched over the sink washing a white shirt. He turns as Henry enters and broadcasts a tight grey smile. That too small head and overly long neck makes him jump.</p><p>“Oh, hello, Mr Kikker.” Detective Jansen applies more hand dispenser soap to the shirt collar. “I guess you&#39;re surprised to see me.”</p><p>Henry tries to talk but only a croak emerges. His throat feels packed with gravel.</p><p>“Please go about your business. No need to be shy. We&#39;re all lads here.” Jansen winks.</p><p>Henry locks the stall door and sits down on the seat. The detective stands on the toilet in the next cubicle and peers down at him.</p><p>“You&#39;re probably wondering what I&#39;m doing here,” he sighs and shakes his head. “My own fault really. My boss wasn&#39;t too happy about me giving you an extra two weeks to find the book. After I left you, I learned that three inmates had suffocated under a collapsed pile in mulch processing. We now have a worker shortage in the library. Tragic circumstances, though one you could have ameliorated if I had just taken you in. I&#39;m not allowed to go home now until your case is resolved. I still have to give you the two weeks since that&#39;s what I entered in the official report,” he says ruefully. “I&#39;d haul you in right now if I could, but, you know, bureaucracy.</p><p>“My Sally is pretty pissed off. We have three kids you know, all of them grown up with families, but all of us living in the same house. They can&#39;t afford to leave. Sally needs me to handle them since they don&#39;t listen to her. But they don&#39;t actually listen to me either.  </p><p>“You and your generation are all so damn lazy. It&#39;s not your fault. It&#39;s just the way you were raised. All this technology just acts for you. You don&#39;t have to put in any effort in the call centre. The machine just talks for you.</p><p>“Anyway, I&#39;m going on a bit. I just came by to tell you that I will be on your case doing whatever it takes to get you to find that book.” He sets his lips into a tight line.</p><p>Henry leaves the restroom, bladder carried between his hips like a bowling ball.</p></FadeIn>
      )
    } else if (props.courseGoals.length === 10) {
      action = (
        <FadeIn><h1>*Are these interruptions irritating?*</h1><h1>*Why do they irritate you?*</h1><h1>*Do you hate this society?*</h1><h1>*Or does society hates you?*</h1></FadeIn>
      )
    } else if (props.courseGoals.length ===11) {
      action = (
        <FadeIn><div className='video'><iframe src="https://www.youtube.com/embed/Issz8pLepEU?controls=0"title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" ></iframe></div>
        
        <div className='videoDialogue'><h3>This time it is Vrocum who is frustrated by the speaker interrupting the telenovela. He thinks of the vampire executive in their towers feeding on his attention.</h3><h3>He walks to the window and stares out at the moribund garden.</h3></div></FadeIn>
      )
    } else if (props.courseGoals.length === 12) {
      action = (
        <FadeIn><h3>Panlaughlin drags him away from the window and sits him down, holds him so he can't get up. He is determined that they see this through to the end.</h3><h3>They will continue watching, though it feels like a struggle.</h3><h3>Vrocum's legs shake uncontrollably. He speaks with a shaky voice to power the TV.</h3></FadeIn>
      )
    } else if (props.courseGoals.length === 13) {
      action = (
        <FadeIn><p>* * *</p><p>Three days later a package arrives at his home, containing a pillow and headset. He is to record his dreams and send them back to Nocturne. If they are particularly surreal and vivid, the company will pay for their syndication. Henry could never remember his dreams, but he is certain that they must be wild for no other reason than he believes he is a creative sort with a deep and expansive emotional life that lay beyond his conscious grasp.</p><p>“You really think you&#39;ll be able to sell your dreamscapes?” Simon scoffs. He eats dinner while shirtless on the sofa. On his plate is a beige melange of food substitutes. In the digital realm, he sits at a table in a bustling medieval banquet hall. “That&#39;s wild. You really think a lot of yourself. There are people ingesting psychedelics and listening to the sound of their parents making love in order to get the weirdest dreams possible. You can&#39;t compete, Henry. These ideas of yours are terrible.”</p><p>Henry&#39;s phone rings. It&#39;s his mother.</p><p>“There is a man here!” She is agitated. “He says he&#39;s a detective from the library and has locked your father in the garden shed. He claims that he is doing it to incentivize you. What trouble have you gotten into now, Henry?</p><p>“He said something about a library book. That you forgot to return it. Really, Henry, you need to have your memory checked out. I know you have said that your forgetfulness is no more serious than other people of your age, but I think you have early onset dementia.</p><p>“This Detective has been harassing your father at work. Eating his lunch from the staff fridge, throwing wet paper towels around the office.</p><p>“Oh God! Your dad is calling for me, telling me to phone the police. I better go.</p><p>“Don&#39;t be expecting us to help you in this situation, Henry. Even if you go to jail, we will not fork out another penny for you. Do you know how much in debt we are in at the moment? We may lose the house. We should have never agreed to be the guarantors for your foolish stay in that stasis pod.</p><p>“I have so many regrets, Henry. So many regrets.”</p><p>* * *</p><p><em>Dear Mr Kikker</em>, the e-mail reads, <em>we have reviewed the footage you have sent us, but unfortunately it does not conform to our standards of variety and interest. We receive many submissions and most are unsuitable so we encourage you not to feel bad that we did not accept it on this occasion. Worryingly, your dream avatar seeks to burn absolutely everything to the ground; from your home and the people in it, to your workplace and your colleagues. Please call 0837 979 983 to speak to a member of our counselling team and they will talk you through this proclivity for dream arson. Calls cost £80 a minute. We will return your USB stick with your dream samples. You may keep this for your own records. Be well. Nocturne HQ.</em></p></FadeIn>
      )
    } else if (props.courseGoals.length === 14) {
      action = (
        <FadeIn><p>Henry shuts his laptop and presses his palms into his eyes. Simon is in the living room climbing the walls and ceiling using the Human Spider shoe and glove set he had bought the day before. Another gadget that Simon would tire of after a few days.</p><p>“I can hear you sighing through there!” Simon yells. “I take it they didn&#39;t want your dreams. I told you so.”</p><p>The door swings open and Simon clambers onto the bedroom ceiling on all fours, hair hanging down, hands sheathed in red gauntlets.</p><p>“I feel like a damn superhero!” He exclaims, then upon seeing Henry&#39;s frown, Simon drops onto Henry&#39;s bed and stands over him. “I hear there&#39;s a new loan place at the end of the high street. You might want to go there. They have an interesting offer. They&#39;ll be able to cut you a cheque for the next two or three paydays. Won&#39;t that be enough to get your social media license? I&#39;ll come with you.”</p><p>* * *</p><p>The shop is called Highway Deposits. Its frontage is an eye-watering neon that makes the rusting cars, and denuded trees outside look as if they are sliding out of reality into oblivion.</p><p>Simon and Henry sit a desk staffed by a tall elegant young man in a well-fitted suit. He smiles assuredly and nods often at random intervals as if he is programmed to do so.</p><p>Henry takes out his ID card and payslips with shaking hands and is about to speak when his flatmate cuts in.</p><p>“So, my friend here is looking for a loan.” Simon leans one elbow on the desk. He wants to make sure that the teller understood that he, Simon, is doing all this for a lark. Money is not an issue for him. “He needs around £1200 so he can buy a social media license and find out what he was doing fifteen years ago.”</p><p>The clerk presses a few keys and swipes Henry&#39;s ID card over a reader.  </p><p>“Well Mr Kikker,” he says finally. “It looks like we can help you today with a few provisos. Admittedly your credit rating isn&#39;t the best so we can&#39;t just give you the money. You qualify for our heart donation scheme, whereby if you donate your heart to Highway Deposits, we will debit your account to the tune of £1400.</p><p>“Of course,” the teller smiles gently, “you may have some misgivings. First of all, we would actually replace your heart with a mechanical one. The ZX-867 is a handsome mid-range model which is guaranteed to work for the first year. You may have to purchase a better model in a couple of years but they are always improving in quality.”</p></FadeIn>
      )
    } else if (props.courseGoals.length === 15) {
      action = (
        <FadeIn><p>From out of the teller&#39;s jacket, a wire hangs down that disappears into the floor.</p><p>“What do you think Henry?” Simon gently punches him on the arm. “Does that sound good to you?”</p><p>Henry had heard of people with these mechanical hearts dropping dead during thunderstorms. He looks down at his hands. They were curiously inert, twitched by minute electric currents from his brain. If he didn&#39;t move them, he couldn&#39;t feel them at all.</p><p>“I think he&#39;ll take the deal.” Simon slaps the desk. “He really needs the money. Whoa! What the hell are you doing?!!”</p><p>Henry tips Simon sideways out of his chair onto the floor and steps over him on the way to the door.</p><p>Outside the soft evening air ruffles his clothing. He wants to cry but can&#39;t.</p><p>His phone rings.</p><p>“It&#39;s a disaster Henry!” His mother says. Her voice is worn and tired, as if she has spent all evening shouting at a wall. “Your father has been fired from his job. That interfering detective downloaded pornography on his work computer. The landlord found out and now we have to move out the house by the end of the week. All thanks to you and your silly lifestyle. Your dad and I are having to move to an Eddie Town. That&#39;s right! We&#39;re going to live on the sea in a floating barge amidst other floating barges. Goddamn you, Henry.”</p><div className='images'><img src={Image3} alt='on the phone'/></div></FadeIn>
      )
    } else if (props.courseGoals.length === 16) {
      action = (
        <FadeIn><h1>*When we drink, you drink also*</h1><h1>*We are all in this together*</h1><h1>*When we share, we care for each other*</h1><h1>*Honesty. Just that.*</h1></FadeIn>
      )
    } else if (props.courseGoals.length ===17) {
      action = (
        <FadeIn><div className='video'><iframe src="https://www.youtube.com/embed/D7tJHOpWolM?controls=0"title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" ></iframe></div>
        
        <div className='videoDialogue'><h3>Panlaughlin laughs at the interruption then quickly stifles it by burying his mouth in his sleeve. To laugh at the speaker is to invite trouble.</h3><h3>He remembers a hamster he had once. He envied its freedom.</h3><h3>The thought invites an additional chuckle.</h3></div></FadeIn>
      )
    } else if (props.courseGoals.length === 18) {
      action = (
        <FadeIn><p>When he arrives home Simon laughs and slaps Henry repeatedly on the shoulder. He has never seen Henry angry before and finds it all very amusing. By way of apology Simon says that he will talk to his brother and get him an audience with the local Space Witch, who ran a criminal enterprise out of a park across town.</p><p>Henry waits at the park gate the next day nervously eyeing the guard. Their body has been artificially broadened, arms around his slim torso enlarged to gargantuan coils, obscene hands like oars dangling at their ends.</p><p>“No talking to the Space Witch,” says the guard. “Nod. Shake your head. Don&#39;t speak. We have snipers watching everything.”</p><p>The park is deserted. The yellow grass grew long amid bare patches. A distant sizzling sound suggests that everything is in the process of being burned away slowly.</p><p>A blonde child on the swings cuts a small lonesome figure against the sprawl of unused playpark, much of it rusting and fallen to pieces. Henry walks towards the tight-lipped little girl who urges herself back and forth, eyes lost in contemplation.</p><p>“I hear that you&#39;re looking for some extracurricular work.” The voice is that of a fully-grown woman rasped by alcohol or tobacco. She delicately undoes the wrapper of a chocolate bar with two fingers. “It just so happens we have something you can do for us. I was interested to see that you have trained as an actor.”</p><p>With the chocolate bar in her mouth, she takes out a photograph from the chest pocket of her dungarees and holds it up, glances at it and Henry beyond. She smiles with chocolate lips.</p><p>“Perfect!” She mumbles before pocketing the photo. “Almost twins.”</p><p>The little girl stands up on the swing and urges herself back and forth. Her dungarees show grass stains all down the front.</p><p>“What do you think? You get to act! I read a review of one of the shows you did a long time ago that said you had excellent vocal control.”</p><p>Henry nods solemnly and then smiles despite himself. It had been a long time.</p><p>“Alright then, the details will be given to you a few days before. Oh yes,” the girl says as she jumps off. “It was mentioned that you needed an advance.”</p><p>She makes a twirling motion with her fingers to whomever is watching.</p></FadeIn>
      )
    } else if (props.courseGoals.length === 19) {
      action = (
        <FadeIn><p>“Well we can do that. Give your bank details to Marvin at the gate.”</p><p>Her face turns serious, an expression that seemed petulant on a child: “Of course, if you back out once this advance is transferred, we will sell all your organs and then come to collect them. Understand?”</p><p>He nods. What else could he do?</p><p>* * *</p><p>The next day he logs in and pays his bank to show him a statement. He reads the numbers and holds out his hands to the sky with his eyes closed as if receiving God&#39;s beneficence. He has enough to access the last twenty years of social media data. He immediately buys a licence.</p><p>Flicking through the photos on his old FB account, he realises how little of that time is reflected in his current situation. None of the faces alongside his in photographs are familiar to him anymore. He looks happy and animated, wearing an array of costumes, his poses describing multiple personalities. His body and expression had ossified in the intervening years. All that remained were vague memories now of bright lights and darkened stages, staring out at silhouettes of people dimly expectant.</p><p>His eyes flood with tears.</p><p>Simon sits on the couch across the room trying on his new trainers. They are limited edition Flower shoes with retractable wheels and sub-woofers in the heel.</p><p>“What do you think of these?”</p><p>Henry shrugs.</p><p>Simon hugs them to his face, inhales deeply from one of the shoes. He brings them over to the table and asks Henry to sniff them too. </p><p>Henry glares back.</p><p>“Ah! I see you have your license back now.” He takes the mouse from Henry&#39;s hand and scrolls down. “Well, buddy, it appears as though you had a massive sale of all your stuff around thirteen years ago. The library book was probably in amongst that. We can check out who attended the event and message them.”</p><p>Simon shoves him aside and types out a message, his eyes avid and glistening. Henry fetches his bottle of Guzzle Guzzle out of the fridge.</p></FadeIn>
      )
    } else if (props.courseGoals.length === 20) {
      action = (
        <FadeIn><p>“You want to do that now?!” Simon exclaims.</p><p>* * *</p><p>Fitz lives on a roof in one of the upscale neighbourhoods. On the main street, ninety percent of the people are old and wear exoskeletons that increase their strength and speed. Many bound along on the pavement like gazelle.</p><p>Henry presses the door buzzer. A grinning face appears on the intercom screen. The head is more filled out but Fitz still has the same well-defined black goatee and piercings in both ears. Henry had completely forgotten Fitz existed until he saw his face on the computer the night before. They were best friends for a few years.</p><p>The lift opens onto a roof terrace presided over by a squat gnarled tree. Lights are strung in its branches illuminating ornate birdboxes. In front of it on a four-foot high square concrete base is an incredibly detailed model village.</p><p>A small action figure sits with its legs dangling off the edge and only when Henry approaches does he notice the other figures milling around the model village. The sight gives him vertigo as if his brain can only comprehend these tiny humans as being far away. He has never seen one of these Lilliputian villages in real life. The six-inch high figure waves to him and as Henry approaches, he realises it is Fitz.</p><p>Henry kneels in front of him, speechless.</p><p>“I realise it&#39;s a bit of a shock to see me like this,” Fritz adjusts his tie. “I always get a kick out of surprising people who don&#39;t know I&#39;ve done it.</p><p>“It&#39;s true. I&#39;ve gone through the shrinkage procedure. People told me it was a bad idea and that it was irreversible but I don&#39;t regret a thing.” Fitz looks off into the far corners, lost in thought. “There are dangers of course, from birds mostly. Seagulls are a real problem. I&#39;ve known people who have been eaten. We now have drones watching out for us so at least that&#39;s something. You should join us. The procedure is pretty expensive but it&#39;s definitely worth it if you want to save in the long run. I own the land my house is built on and food is so cheap when you get to this size. One hamburger is enough to feed twenty people. I still do theatre as well. I teach classes and put on my own plays. Most people here work in IT. I&#39;m going on about myself, but how are you, old pal?”</p><p>Fitz looks him up and down, eyes catching on the outbreak of hives that mar Henry&#39;s face with blisters and scabs, the dirty worn-out hoodie, the stained and ripped jeans.</p></FadeIn>
      )
    } else if (props.courseGoals.length === 21) {
      action = (
        <FadeIn><p>“I can see you&#39;re not doing so good. The world out there is chaos. You still act? I was as stressed out as you look, but once I shrunk myself down, everything worked out. We appreciate the smaller things because we&#39;re smaller,” he grins at this quip.</p><p>“Anyway, about the book,” he mutters. His face grows red. “I still have it but like the rest of my possessions, I had it shrunk down.”</p><p>From his little knapsack he takes out a one-inch tall copy of Wide Sargasso Sea and holds it out to Henry who pinches it between his thumb and forefinger.</p><p>He imagines himself sitting in the library jail after a long day digging in the mulch works. It seems the universe doesn&#39;t want him to be free.</p><p>“Really sorry about that,” Fitz shrugs his shoulders. “But you probably shouldn&#39;t have been so careless. Selling all your possessions to produce that terrible play you wrote was a bad idea. I could see that at the time.”</p><div className='images'><img src={Image4} alt='tinyMan'/></div></FadeIn>
      )
    } else if (props.courseGoals.length === 22) {
      action = (
        <FadeIn><h1>*Just a few words*</h1><h1>*Formulate your reality so it can be understood*</h1><h1>*A sliver of truth in the mundane fabric*</h1><h1>*The world is hungry*</h1></FadeIn>
      )
    } else if (props.courseGoals.length === 23) {
      action = (
        <FadeIn><h3>Panlaughlin and Vrocum hold hands. They can get through this. Every cell in their body is crying out for them to move, to fixate on something else.</h3><h3>Vrocum fears he has wet himself, whilst Panlaughlin simply wants to distract himself by looking at his phone and scrolling through videos of cats.</h3></FadeIn>
      )
    } else if (props.courseGoals.length === 24) {
      action = (
        <FadeIn><p>* * * </p><p>Henry places the thumb sized book in an envelope addressed to Detective Jansen at the National Library and leaves it on the dining table with a note telling Simon to post it if he is arrested. It wouldn&#39;t make any positive difference to his case if everything went awry, but it would suggest that he had tried to get the book back in its original form. Hopefully, it wouldn&#39;t need to be sent and with his takings from his work for the Space Witch he would be able to buy the slightly newer edition of Wide Sargasso Sea he had seen online.</p><p>The fake ID, the disguise, lenses, and transmitter sent by the Space Witch are delivered that morning. The temporary splints in his face alter his appearance to resemble that of Richard Mulgrew, a local landlord and businessman.</p><p>Henry walks taller as he leaves his flat.</p><p>He imagines how Richard Mulgrew feels as a landlord; assertive, moneyed, and possessed of a great internal wave that moves perennially forward.</p><p>Henry braces himself before walking in through the door of the council headquarters, breathing steadily, humming loudly in echo of the exercises he had learned at drama school. Through those revolving glass doors is the stage.</p><p>He greets the person at the reception with a big effusive Hello that sounds completely unlike himself, and he presents the fake ID card by slapping it down on the desk. He imagines his presence expanded out to a large glowing cloud that takes up the entirety of the room. Others sit waiting on benches arrayed around its sides. They are not as important as him.</p><p>Only a moment later, a person representing the council Dreamcaster department enters. She introduces herself as Ms Olaf. Her bearing is officious and stripped down, as if she contains a huge amount of bureaucratic power that her small body can barely contain.</p><p>She sits down opposite him at a mahogany table in one of the rooms upstairs.</p><p>“Mr Mulgrew,” she says. Her spindly fingers are interlaced before her. “I am glad that you have come back to reconsider our offer. I believe you were worried that putting a Dreamcaster Emergency Broadcast dish on your downtown buildings would be an eyesore and dissuade people from renting your apartments. We have addressed this and have ensured that the dish will be significantly smaller than first projected.”</p></FadeIn>
      )
    } else if (props.courseGoals.length === 25) {
      action = (
        <FadeIn><p>Henry nods and reads the lines presented to him through the lenses: “I understand your Dreamcaster system is only to be used to wake people during times of emergency, for deaths in the royal family, terrorist incidents, natural disasters and the like.” The cut glass accent emerges from an unnatural place at the back of the throat. “As well as the agreed fee for rental of the roof spaces, I was wondering if I could possibly have access to the Dreamcaster system itself. I know what you&#39;re really doing with that equipment. And I want in on it.”</p><p>The request sits on the table for a few moments, gathering density. Her dark eyes flicker.</p><p>“If you allow us to put a dish on the roof of all your city properties,” she says, “then perhaps we can accommodate you. As you know, these are austere and difficult times and what you are asking for could be problematic for both of us.”</p><p>He feigns consideration then assents.</p><p>A few moments later they are in the basement of the building. Ms Olaf uses a key card to open a door where the Dreamcaster system sits behind a large pane of reinforced glass. Panels are arrayed around a large cylinder that ascends into the ceiling. In front of it are three terminals where a man in a brown corduroy jacket sits with his face leaning into the screen typing code.</p><p>“Jarrod here is setting up the system for this evening&#39;s broadcast,” Ms Olaf says wearily. “As well as broadcasting emergency messages into the dream space, we can also broadcast subtle advertising and other types of messages. As you probably know, this is very illegal, but we allow local businessmen like yourself access to it in return for certain favours. At the moment we are sending out good feelings about the council cutting down a clutch of ancient apple trees in a Greton Park so we can sell the land to a Swiss property developer. We have a few other ongoing adverts going out on the broadcast. Did you notice that all the young people want those Flower trainers, the ones with the sub-woofer in the heel? Well, people have been dreaming about them for the past month.”</p><p>Ms Olaf and Jarrod both wear tight-lipped cynical smiles.</p><p>“How does it all work?” He asks Jarrod.</p><p>Jarrod explains that the system used alternating magnetic and electrical currents. He points to a small USB port at the back of each terminal where dreams could be loaded up.</p><p>Henry sticks a wood coloured sticker to the underside of the desk in front of him. It is a transmitter that would allow the Space Witch gang to listen in on whatever went on in this room. They hope to use this to press on some of the local businesses using this illegal operation.</p></FadeIn>
      )
    } else if (props.courseGoals.length === 26) {
      action = (
        <FadeIn><p>Ms Olaf suddenly appears horrified: “Mr Mulgrew! Your nose is bleeding!"</p><p>One of the splints has snapped in his nose and makes his nostrils lopsided. Blood seeps out. Henry panics, covers his face with his hand whilst Ms Olaf runs out to get him some tissues.</p><p>The monitor emits a steady beeping sound. Perhaps the transmitter has been discovered.</p><p>Henry doesn&#39;t know whether to run or stay seated. Jarrod kneels under the table among the trailing wires and fiddles with the hard drive, turning the computer off and cutting the shrill alarm.</p><p>“I just need to give it a few moments,” he says calmly, “then turn it on again.”</p><p>Through the glass sits the Dreamcaster hard drive, large and inert, yet imbued with an awesome power. Henry takes the Nocturne USB from his pocket and vacillates for a moment before he stabs it into a port behind the second monitor.</p><p>* * *</p><p>The detective with his small head and big body walks into the office followed by two large librarians in corduroy blazers.</p><p>Henry feels a chill against his back, a sense of shadows looming, and turns to the triumvirate and nonchalantly holds up his finger while he finishes up the call. Jansen juts out his too small head, affronted by Henry&#39;s insouciance.</p><p>“All our call centres are UK-based and our electricians are specially equipped to deal with any problems that might arise twenty-four hours a day. Do you have any more questions?” Pause. “Excellent. Well if you think of anything later, you have my number. Have a good day, sir.”</p><p>Henry lifts off the prosthesis and grins, wipes the sweat and saliva around his mouth with a paper towel.</p><p>“Mr Kikker,” the detective rocks back on his heels. “You are under arrest under section 44 of the Library Code. Failure to return a book. Namely,” he holds up a hand to his face where some writing is scrawled on his palm, “one Wide Sargasso Sea by Jean Rhys, which the library loaned you on...”</p><p>Henry quickly steps to his desk drawer a few metres away and draws the book out of the drawer. The detective looks from the book to him. Vague disappointment on his lips.</p><p>“Well, well. Impressive, Mr Kikker,” he sas as he flicks through the pages. “This must&#39;ve been expensive. I have no idea how you acquired this, but it is indeed a fine edition. I guess I&#39;ll have to accept it,” he rubs at his forehead. “The boss is going to kill me but I guess there are plenty more offenders out there.”</p></FadeIn>
      )
    } else if (props.courseGoals.length === 27) {
      action = (
        <FadeIn><p>He smiles defeatedly showing tiny yellow teeth.</p><p>“How are you otherwise?” Jansen says.</p><p>He sits down on one of the desks and dismisses his associates with a wave of the hand. Henry&#39;s colleagues, who had been expecting some physical resistance on Henry&#39;s part, turn back to work disappointedly. </p><p>“Are your parents okay? I&#39;m sorry your father was fired. My boss was pressuring me to pressure you and you know what it&#39;s like. Every person above is constantly shitting down on the person below. Way of the world.”</p><p>Henry had tried to wire his parents some money so they could get back to the mainland, but they had sent it back in cash through the post.</p><p>“Things aren&#39;t so great on my end,” Jansen says, not waiting for Henry&#39;s reply. He unbuttons his collar and loosens his tie. “My eldest son was arrested for arson. Burned out the neighbour&#39;s car. He had been arguing with them the day before about parking in front of our gate. I don&#39;t know what he was thinking. There have been fires in the library too. We&#39;re not sure if they&#39;re deliberate. It seems to be part of a pattern. People are burning things left right and centre. Multiple cases of arson. Have you noticed?”</p><p>Henry realised he didn&#39;t have to listen to the inspector anymore and turned away with a smile. He had more calls coming through on the switchboard.</p><p>“Anyway goodbye, Henry,” Jansen said, his expression maudlin. “Take care.”</p><div className='images'><img src={Image5} alt='city on fire'/></div></FadeIn>
      )
    } else if (props.courseGoals.length === 28) {
      action = (
        <FadeIn><h1>*We need each other*</h1><h1>*We are mutually sustaining*</h1><h1>*Binary star systems*</h1><h1>*Without us, no more toys*</h1></FadeIn>
      )
    } else if (props.courseGoals.length === 29) {
      action = (
        <FadeIn><h3>Panlaughlin and Vrocum watch the credits roll.</h3><h3>They press their heads together and dream of everything they have seen and everything that might be.</h3><h3>They know that this is a temporary space. Soon they will begin to tremble for some new distraction, but for the moment they try to be free.</h3></FadeIn>
      )
    } else if (props.courseGoals.length === 30) {
      action = (
        <FadeIn><div className='video'><iframe src="https://www.youtube.com/embed/TUe1-60d9zY?controls=0"title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" ></iframe></div>
        
        <div className='videoDialogue'><h3>And then Panlaughlin plays them a video on his phone...</h3></div></FadeIn>
      )
    } else if (props.courseGoals.length === 31) {
      action = (
        <FadeIn><h1>The End</h1></FadeIn>
      )
    }

  return (
      <div className='directions'><p>{action}</p></div>
    
  )}

export default StageDirections;

