import React from 'react'
import './StageDirections.css';
import FadeIn from '../CourseGoalItem/FadeIn';
import Image1 from '../Images/beyond.webp'
import Image2 from '../Images/drinkingGuzzle.png'

const StageDirections = (props) => {

  let action;
  if(props.courseGoals.length === 0){
    action = (
        <FadeIn><div className='directions'><h3>Panlaughlin and Vrocum settle down in their sparsely-furnished living room to watch a banned telenovela. Those caught watching it face up to 50 years in prison.</h3><h3>To keep the electricity running, they must talk incessantly.</h3><h3>Our collective dreams are of great worth to the corporations.</h3></div></FadeIn>
    );} else if (props.courseGoals.length === 1) {
      action = (
        <FadeIn><h1 className='titleName'>FIRESALE: A Telenovela</h1><img src={Image1}/><h2>by David Valdez Taylor</h2></FadeIn>
      )
    } else if (props.courseGoals.length === 2) {
      action = (
        <FadeIn><h3>The story begins...</h3><br></br><p> “Well, sir. Since we installed our more accurate meter reader, we have discovered that you use far more electricity than assumed under the previous tariff. We would be willing to discuss a different payment plan that will save you money in the long run. Is this something you would be interested in?”</p><p>Black rubber around Henry&#39;s throat palpates his vocal cords while electric needles jounce his tongue. He tries to avoid his reflected gaze in the office window&#39;s mirrored surface. Cold water runs down his wrist to the elbow as he sponges more soapy water onto its surface. His reflection momentarily wavers.</p><p>Mrs Stephens appears below and waves frantically for him to come down. He presses a button that lowers the cradle to the ground.</p><p>“The rates we have quoted will remain in place until April 2078, then will review the situation so there is nothing for you to worry about. You should receive an e-mail within the next week with your revised plan. Thank you and enjoy the rest of your day.”</p><p>Henry pulls the tubing out of his mouth and spits the taste of rubber into the rhododendrons.</p><p>“There&#39;s somebody waiting to speak to you in reception. It looks official.”</p><p>She is displeased, her hair a nest of white curls that shuffles in the wind like a restless mammal.</p><p>This interruption, she states, will come out of your wage.</p><p>A middle-aged broad-shouldered man in a black suit and tie waits by the desk. His neck is stretched to its utmost atop which sits a small bald head furiously chewing gum.</p><p>“Mr Kikker, I presume?” He says. His hands remained firmly clasped behind his back as Henry reaches for a handshake. “I am Detective Jansen,” he draws out a tattered blue lanyard. Details on the card have faded to a meaningless grey smudge. “I work for the Library Investigations department. You better take a seat!”</p></FadeIn>
      )
    } else if (props.courseGoals.length === 3) {
      action = (
        <FadeIn><p>He declares the last loudly to Henry and, by an inclination of his head, to the rest of the room. Toby on the reception desk films them with his smartphone.</p><p>“Oh, dear, Henry!” Mrs Stephens stands by the door, hands on her hips. “What has he done?”</p><p>“This young man borrowed a copy of Wide Sargasso Sea by Jean Rhys fifteen years ago and never returned it,” Jansen thrusts his hands into his pockets and shrugs as if all the evils he had seen has made him lose faith in humanity. “People think that we will never catch up with them and they can change their address or move away. Our arm is long, however. Long and unrelenting.”</p><p>To illustrate this point, he rolls up one shirtsleeve and thrusts out a long pale arm at Mrs Stephens upon which is tattooed a large watchful eye. She and Toby nod appreciatively.</p><p>Henry dimly recalls having used the library several times in his youth.</p><p>His colleagues emerge from the entrance to the office drawn by the activity in reception, the headsets that make them look like anthropomorphic crocodiles are on pause as they nod and point at the intricate tattoo.</p><p>“What can he do?” Mrs Stephens says, now laying her hand on Henry&#39;s shoulder. He flinches. She was keen to take on the appearance of a good boss, always on the workers side, but only when she had an audience. “You see, Mr Kikker here only came out of a stasis pod two months ago. He was in there for four years unemployed, only taking one meal a day to conserve energy and sleeping the rest of the time. He must have borrowed the book before the library was sold off?”</p><p>“We inherited all the library debts,” says Jansen, his shoulders drop. “We had to sell off most of the stock. We only have four books left in the city&#39;s whole library system.”</p><p>Jansen sits down on the bench.</p><p>“My sister was in a stasis pod for a few months. It&#39;s no way to live.” He sighs exaggeratedly. “I shouldn&#39;t do this, but I&#39;m going to delay your arrest. Normally I would simply process you here and now. Instant conviction and sentencing. Off to our gulag! I have that authority!” He boasts.</p><p>Jansen declares to the small crowd standing behind the reception desk that he will give Henry two weeks to find the book or a replacement and bring it to the library in lendable condition. Failure will see him carted off to the book mines for five years and a day, such was the mandated punishment.</p><p>He points at Henry for an uncomfortable length of time, his thick eyebrows downturned in warning, before he hands over a citation and marches off through the glass doors.</p><p>Mrs Stephens shoos the gawkers back to work.</p><p>Henry, hands outstretched, looks to say something to her.</p><p>“Don&#39;t say sorry! Get back outside and wash those windows, Henry,” she says. “Those calls won&#39;t answer themselves.”</p><p>* * *</p></FadeIn>
      )
    } else if (props.courseGoals.length === 4) {
      action = (
        <FadeIn><h1>*Speak more*</h1><h1>*Enunciate your words*</h1><h1>*Be productive*</h1><h1>*Dream big!*</h1></FadeIn>
      )
    } else if (props.courseGoals.length === 5) {
      action = (
        <FadeIn><div className='video'><iframe src="https://www.youtube.com/embed/k5Kd1jn84V0?controls=0" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" ></iframe></div><div className='videoDialogue'><h3>Panlaughlin is disheartened by the voice broadcasting from the wall speaker and turns his attention away from the telenovela to watch a video on his phone, of himself as a young man.</h3></div></FadeIn>
      )
    } else if (props.courseGoals.length === 6) {
      action = (
        <FadeIn><h3>Vrocum snatches at the phone and directs Panlaughlin's attention back to the big screen.</h3><h3>Such sentimentalism is everything they are trying to escape from.</h3></FadeIn>
      )
    } else if (props.courseGoals.length === 7) {
      action = (
        <FadeIn><p>Henry barrels into the kitchen to get his bottle of Guzzle Guzzle from the fridge. Hives have broken out in itchy and unsightly blotches down his nose and cheeks. His flatmate, Simon, sits on the couch and stares blankly forward, his gaze lost to his MMORPG where he is an elf or some such creature. The VR lenses stain his eyes creamy white.</p><p>The Guzzle Guzzle saturates Henry&#39;s mouth in its bittersweet wash and he momentarily forgets about his anxiety.</p><p>He can&#39;t remember anything about Wide Sargasso Sea. He remembers next to nothing about any book he has read.</p><p>A feeling of expansiveness rises in his chest as the chemical flow makes him feel heroic, like a giant clambering effortlessly over rocks and shoals through a drunken sea.</p><p>“Guzzle Guzzle is not supposed to be drunk every day, Henry.” Simon rubs at his red streaming eyes, lenses now extracted. “It&#39;ll give you early Alzheimer&#39;s.”</p><p>Henry tries to respond but can only drool at this moment.</p><p>Simon picks up Henry&#39;s citation and reads it quickly, his eyes widening as he reaches the end.</p><p>“Well, then,” Simon mutters, “it looks like I&#39;m going to have to find a new flatmate.” He brings the letter closer to his face as if trying to find some watermark that will guarantee its authenticity. “I&#39;m guessing that the book is irretrievably lost. Those library people don&#39;t fuck around, Henry. You&#39;re going to have to steal a replacement. There&#39;s no way you can afford to buy one.</p><p>“I think you&#39;ve gone about living your life all wrong and this is just another result of the terrible decision you made in studying Drama at university,” he leans back as he prepares to digress on this most delectable topic. He had brought it up several times in the past month after he had found Henry&#39;s degree under the utensils in the kitchen drawer.</p><p>“Practical systems of thought are what is in demand. You should&#39;ve done computer programming or economics or business studies, not wishy-washy arts. You must be utterly exceptional to succeed in that field. I&#39;ve known you for a long time and you are not exceptional.</p></FadeIn>
      )
    } else if (props.courseGoals.length === 8) {
      action = (
        <FadeIn><p>“Even fifteen years ago, books were passé. What were you thinking?! Neuroblasting direct entertainments is all that there is or should be.</p><p>“My brother is a lawyer, you know, but I don&#39;t think even he can help you appeal. It&#39;s an open and shut case. I can&#39;t help that your memory is also screwed by the Guzzle Guzzle and all that time in a stasis pod. You should try and get your social media license reactivated so you can find out what you were doing at the time.”</p><p>Henry sits down heavily on the couch. The combination of having his mouth talked all day and the Guzzle Guzzle makes his tongue feel like a large cold slug. He clasps it between thumb and forefinger.</p><p>“Fifteen years ago!” Simon raises his eyebrows in astonishment. “You may as well try to remember the Stone Age. Getting a social media license going back that far will cost a bomb. Even mine only goes back two years and I can&#39;t remember anything past maybe seven years. You&#39;re going to have to get another job or something. Maybe use that to leverage a loan. And before you ask, I can&#39;t lend you any money,” he frowns. “I&#39;d never get it back.” </p><div className='images'><img src={Image2}/></div>
        </FadeIn>
      )
    } else if (props.courseGoals.length === 9) {
      action = (
        <FadeIn><p>* * *</p><p>Henry activates the bathroom break protocol and takes off the prosthetic. The computer screen in front of him displays a countdown from five minutes. He tries not to look around, seeing a depressing reflection of his own bleak situation in the dark-ringed lifeless eyes of his colleagues, even though the room echoed with their bright cheery voices.</p><p>Inside the staff toilets a bald man in a baby blue tracksuit is hunched over the sink washing a white shirt. He turns as Henry enters and broadcasts a tight grey smile. That too small head and overly long neck makes him jump.</p><p>“Oh, hello, Mr Kikker.” Detective Jansen applies more hand dispenser soap to the shirt collar. “I guess you&#39;re surprised to see me.”</p><p>Henry tries to talk but only a croak emerges. His throat feels packed with gravel.</p><p>“Please go about your business. No need to be shy. We&#39;re all lads here.” Jansen winks.</p><p>Henry locks the stall door and sits down on the seat. The detective stands on the toilet in the next cubicle and peers down at him.</p><p>“You&#39;re probably wondering what I&#39;m doing here,” he sighs and shakes his head. “My own fault really. My boss wasn&#39;t too happy about me giving you an extra two weeks to find the book. After I left you, I learned that three inmates had suffocated under a collapsed pile in mulch processing. We now have a worker shortage in the library. Tragic circumstances, though one you could have ameliorated if I had just taken you in. I&#39;m not allowed to go home now until your case is resolved. I still have to give you the two weeks since that&#39;s what I entered in the official report,” he says ruefully. “I&#39;d haul you in right now if I could, but, you know, bureaucracy.</p><p>“My Sally is pretty pissed off. We have three kids you know, all of them grown up with families, but all of us living in the same house. They can&#39;t afford to leave. Sally needs me to handle them since they don&#39;t listen to her. But they don&#39;t actually listen to me either.  </p><p>“You and your generation are all so damn lazy. It&#39;s not your fault. It&#39;s just the way you were raised. All this technology just acts for you. You don&#39;t have to put in any effort in the call centre. The machine just talks for you.</p><p>“Anyway, I&#39;m going on a bit. I just came by to tell you that I will be on your case doing whatever it takes to get you to find that book.” He sets his lips into a tight line.</p><p>Henry leaves the restroom, bladder carried between his hips like a bowling ball.</p></FadeIn>
      )
    } else if (props.courseGoals.length === 10) {
      action = (
        <FadeIn><h1>*Are these interruptions irritating?*</h1><h1>*Why do they irritate you?*</h1><h1>*Do you hate this society?*</h1><h1>*Or does society hates you?*</h1></FadeIn>
      )
    } else if (props.courseGoals.length ===11) {
      action = (
        <FadeIn><div className='video'><iframe src="https://www.youtube.com/embed/Issz8pLepEU?controls=0"title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" ></iframe></div>
        
        <div className='videoDialogue'><h3>This time it is Vrocum who is frustrated by the speaker interrupting the telenovela. He thinks of the vampire executive in their towers feeding on his attention.</h3><h3>He walks to the window and stares out at the moribund garden.</h3></div></FadeIn>
      )
    } else if (props.courseGoals.length === 12) {
      action = (
        <FadeIn><h3>Panlaughlin drags him away from the window and sits him down, holds him so he can't get up. He is determined that they see this through to the end.</h3><h3>They will continue watching, though it feels like a struggle.</h3><h3>Vrocum's legs shake uncontrollably. He speaks with a shaky voice to power the TV.</h3></FadeIn>
      )
    } else if (props.courseGoals.length === 13) {
      action = (
        <FadeIn><p>* * *</p><p>Three days later a package arrives at his home, containing a pillow and headset. He is to record his dreams and send them back to Nocturne. If they are particularly surreal and vivid, the company will pay for their syndication. Henry could never remember his dreams, but he is certain that they must be wild for no other reason than he believes he is a creative sort with a deep and expansive emotional life that lay beyond his conscious grasp.</p><p>“You really think you&#39;ll be able to sell your dreamscapes?” Simon scoffs. He eats dinner while shirtless on the sofa. On his plate is a beige melange of food substitutes. In the digital realm, he sits at a table in a bustling medieval banquet hall. “That&#39;s wild. You really think a lot of yourself. There are people ingesting psychedelics and listening to the sound of their parents making love in order to get the weirdest dreams possible. You can&#39;t compete, Henry. These ideas of yours are terrible.”</p><p>Henry&#39;s phone rings. It&#39;s his mother.</p><p>“There is a man here!” She is agitated. “He says he&#39;s a detective from the library and has locked your father in the garden shed. He claims that he is doing it to incentivize you. What trouble have you gotten into now, Henry?</p><p>“He said something about a library book. That you forgot to return it. Really, Henry, you need to have your memory checked out. I know you have said that your forgetfulness is no more serious than other people of your age, but I think you have early onset dementia.</p><p>“This Detective has been harassing your father at work. Eating his lunch from the staff fridge, throwing wet paper towels around the office.</p><p>“Oh God! Your dad is calling for me, telling me to phone the police. I better go.</p><p>“Don&#39;t be expecting us to help you in this situation, Henry. Even if you go to jail, we will not fork out another penny for you. Do you know how much in debt we are in at the moment? We may lose the house. We should have never agreed to be the guarantors for your foolish stay in that stasis pod.</p><p>“I have so many regrets, Henry. So many regrets.”</p><p>* * *</p><p><em>Dear Mr Kikker</em>, the e-mail reads, <em>we have reviewed the footage you have sent us, but unfortunately it does not conform to our standards of variety and interest. We receive many submissions and most are unsuitable so we encourage you not to feel bad that we did not accept it on this occasion. Worryingly, your dream avatar seeks to burn absolutely everything to the ground; from your home and the people in it, to your workplace and your colleagues. Please call 0837 979 983 to speak to a member of our counselling team and they will talk you through this proclivity for dream arson. Calls cost £80 a minute. We will return your USB stick with your dream samples. You may keep this for your own records. Be well. Nocturne HQ.</em></p></FadeIn>
      )
    } else if (props.courseGoals.length === 14) {
      action = (
        <FadeIn><p>Henry shuts his laptop and presses his palms into his eyes. Simon is in the living room climbing the walls and ceiling using the Human Spider shoe and glove set he had bought the day before. Another gadget that Simon would tire of after a few days.</p><p>“I can hear you sighing through there!” Simon yells. “I take it they didn&#39;t want your dreams. I told you so.”</p><p></p></FadeIn>
      )
    }

  return (
      <div className='directions'><p>{action}</p></div>
    
  )}

export default StageDirections;

